"""Generate untracked credentials for the local Compose stack."""

from __future__ import annotations

import hashlib
import secrets
from pathlib import Path


def _hash_key(raw_key: str) -> str:
    return hashlib.sha256(raw_key.encode()).hexdigest()


def generate_local_config(root: Path) -> tuple[Path, Path]:
    """Create a local environment and least-privilege Prometheus token."""
    env_path = root / ".env"
    prometheus_token_path = root / "observability" / "atlas-prometheus-token"
    existing = [path for path in (env_path, prometheus_token_path) if path.exists()]
    if existing:
        names = ", ".join(str(path.relative_to(root)) for path in existing)
        raise FileExistsError(f"refusing to overwrite existing local configuration: {names}")

    analyst_key = secrets.token_urlsafe(32)
    viewer_key = secrets.token_urlsafe(32)
    api_keys = (
        f"local-analyst:{_hash_key(analyst_key)}:analyst;"
        f"local-metrics:{_hash_key(viewer_key)}:viewer"
    )
    env_path.write_text(
        "# Generated by `make local-config`; never commit or reuse these credentials.\n"
        f"ATLAS_API_KEYS='{api_keys}'\n"
        f"ATLAS_ANALYST_KEY={analyst_key}\n"
        f"ATLAS_VIEWER_KEY={viewer_key}\n"
    )
    prometheus_token_path.write_text(f"{viewer_key}\n")
    env_path.chmod(0o600)
    prometheus_token_path.chmod(0o600)
    return env_path, prometheus_token_path


def main() -> None:
    env_path, token_path = generate_local_config(Path.cwd())
    print(f"created {env_path.name} and {token_path.relative_to(Path.cwd())}")
    print("load client credentials with: source .env")


if __name__ == "__main__":
    main()
